const { Server } = require("socket.io");
const cookie = require("cookie");
const jwt = require("jsonwebtoken");
const userModel = require("../models/user.model");
const aiService = require("../services/ai.service");
const messageModel = require("../models/message.model");
const { createMemory, queryMemory } = require("../services/vector.service");
const {
  chat,
} = require("@pinecone-database/pinecone/dist/assistant/data/chat");

function initSocketServer(httpServer) {
  const io = new Server(httpServer, {
    cors: {
      origin: ["http://localhost:5173", "https://chat-gpt-26.vercel.app"],
      allowedHeaders: ["Content-Type", "Authorization"],
      credentials: true,
    },
  });

  // checked if user is logged in or not
  io.use(async (socket, next) => {
    const cookies = cookie.parse(socket.handshake.headers?.cookie || "");

    if (!cookies.token) {
      next(new Error("Authentication error: No token provided"));
    }

    try {
      const decoded = jwt.verify(cookies.token, process.env.JWT_SECRET);

      const user = await userModel.findById(decoded.id);

      socket.user = user;

      next();
    } catch (err) {
      next(new Error("Authentication error: Invalid token"));
    }
  });

  io.on("connection", (socket) => {
    socket.on("ai-message", async (messagePayload) => {
      if (!socket.user) {
        socket.emit("error", "User session invalid");
        console.log("!!User Session Expired");
        return;
      }

      //saving user message in mongodb and vector generate started together for optimisation

      const message = await messageModel.create({
        chat: messagePayload.chat,
        user: socket.user._id,
        content: messagePayload.content,
        role: "user",
      });

      // 2. Then attempt vector and AI generation
      const vectors = await aiService.createVector(messagePayload.content);

      await createMemory({
        vectors,
        messageID: message._id,
        metadata: {
          chat: messagePayload.chat,
          user: socket.user._id,
          text: messagePayload.content,
        },
      });

      //message converted to vectors
      //access chat history based on last 20 messages
      const [memory, chatHistory] = await Promise.all([
        queryMemory({
          queryVector: vectors,
          limit: 5,
          metadata: { user: socket.user._id },
        }),
        messageModel
          .find({
            chat: messagePayload.chat,
          })
          .sort({ createdAt: -1 })
          .limit(20)
          .lean()
          .exec()
          .then((messages) => messages.reverse()),
      ]);

      // console.log("Retrieved memory:", memory);

      //for short term memory having chatHistory of last 20 messages
      const stm = chatHistory.map((item) => {
        return {
          role: item.role,
          parts: [{ text: item.content }],
        };
      });

      //for long term memory query in PineconeDB in last 5 messages
      const ltm = memory.map((item) => {
        return {
          role: "user",
          parts: [
            {
              text: `
          these are some messages that we have discussed previously create answer on these basis
          ${memory.map((item) => item.metadata.text).join("\n")}
          `,
            },
          ],
        };
      });

      //response generated by AI using STM and LTM
      const response = await aiService.generateResponse([...ltm, ...stm]);

      //send ai message
      socket.emit("ai-response", {
        content: response,
        chat: messagePayload.chat,
      });

      const [responseMessage, responseVector] = await Promise.all([
        messageModel.create({
          chat: messagePayload.chat,
          user: socket.user._id,
          content: response,
          role: "model",
        }),
        aiService.createVector(response),
      ]);

      // response is saved as vector
      await createMemory({
        vectors: responseVector,
        messageID: responseMessage._id,
        metadata: {
          chat: messagePayload.chat,
          user: socket.user._id,
          text: response,
        },
      });
    });
  });
}

module.exports = { initSocketServer };
